<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LTIN436923" failures="2" tests="18" name="com.selenium.test.testCases.TestMain" time="11.686" errors="0" timestamp="2025-06-24T20:07:26 IST" skipped="0">
  <testcase classname="com.selenium.test.testCases.TestMain" name="alertHandle" time="0.021"/>
  <testcase classname="com.selenium.test.testCases.TestMain" name="testURL" time="0.081"/>
  <testcase classname="com.selenium.test.testCases.TestMain" name="testURL" time="0.376"/>
  <testcase classname="com.selenium.test.testCases.TestMain" name="alertHandle" time="0.008"/>
  <testcase classname="com.selenium.test.testCases.TestMain" name="testTitle" time="0.123"/>
  <testcase classname="com.selenium.test.testCases.TestMain" name="testTitle" time="0.243"/>
  <testcase classname="com.selenium.test.testCases.TestMain" name="testSrcStation" time="1.028"/>
  <testcase classname="com.selenium.test.testCases.TestMain" name="testSrcStation" time="0.560"/>
  <testcase classname="com.selenium.test.testCases.TestMain" name="testDestStation" time="0.829"/>
  <testcase classname="com.selenium.test.testCases.TestMain" name="testDestStation" time="0.737"/>
  <testcase classname="com.selenium.test.testCases.TestMain" name="testDateSelection" time="1.792"/>
  <testcase classname="com.selenium.test.testCases.TestMain" name="testDateSelection" time="1.502"/>
  <testcase classname="com.selenium.test.testCases.TestMain" name="selectChoices" time="1.349"/>
  <testcase classname="com.selenium.test.testCases.TestMain" name="selectChoices" time="0.982"/>
  <testcase classname="com.selenium.test.testCases.TestMain" name="availableTrain" time="1.005"/>
  <testcase classname="com.selenium.test.testCases.TestMain" name="availableTrain" time="0.847"/>
  <testcase classname="com.selenium.test.testCases.TestMain" name="testDateSelection2" time="0.134">
    <failure message="expected [28-Jun-25 Sat] but found [29-Jun-25 Sat]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [28-Jun-25 Sat] but found [29-Jun-25 Sat]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.selenium.test.testCases.TestMain.testDateSelection2(TestMain.java:325)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testDateSelection2 -->
  <testcase classname="com.selenium.test.testCases.TestMain" name="testDateSelection2" time="0.069">
    <failure message="expected [28-Jun-25 Sat] but found [29-Jun-25 Sat]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [28-Jun-25 Sat] but found [29-Jun-25 Sat]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.selenium.test.testCases.TestMain.testDateSelection2(TestMain.java:325)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testDateSelection2 -->
</testsuite> <!-- com.selenium.test.testCases.TestMain -->
